name: libc-shm-shim
summary: glibc snap shim to redirect used sharem memory into snap permited path
description: |
   glibc snap shim to redirect used sharem memory into snap permited path

confinement: strict
grade: stable
adopt-info: libpthread
architectures:
    - build-on: armhf
    - build-on: arm64
    - build-on: i386
    - build-on: amd64

base: core

parts:
    libpthread:
        plugin: nil
        source: https://git.launchpad.net/ubuntu/+source/glibc
        source-tag: ubuntu/xenial-updates
        source-type: git
        override-pull: |
            snapcraftctl pull
            snapcraftctl set-version $(git describe 2>/dev/null | awk -F '/' '{print $3}')
            rm -rf manual
            quilt push -afq --leave-rejects --quiltrc=${SNAPCRAFT_PROJECT_DIR}/quiltrc
            sed -i -e 's|curpass =.*|curpass = "libc"|g' \
                   -e 's|build-arch: $(stamp)build_C.UTF-8 |# build-arch: $(stamp)build_C.UTF-8|g' \
                   -e 's|$(stamp)build_locales-all|# $(stamp)build_locales-all|g' \
                   debian/rules
            sed -i 's|$(CURDIR)/debian/tmp-$(curpass)|'"${SNAPCRAFT_PART_BUILD}"'|g' debian/rules.d/build.mk
            git apply ${SNAPCRAFT_PROJECT_DIR}/shm-snap.patch
        override-build: |
            mkdir -p etc
            cp debian/local/etc/ld.so.conf etc/
            unset LD_LIBRARY_PATH
            DEB_BUILD_PROFILES='stage0' DEB_BUILD_OPTIONS='nocheck parallel=$(nproc)' debian/rules build-arch
            cd build-tree/*-libc
            make install -j$(nproc)
            cd ../../
            find lib -name 'libpthread*.so*' -exec cp --parents \{\} ${SNAPCRAFT_PART_INSTALL} \;
        build-attributes:
            - no-patchelf

    # dummy part to trigger auto build when glibc updates
    glibc-dummy:
        plugin: nil
        stage-packages:
             - libc6
        stage:
             - -*
        prime:
             - -*

build-packages:
    - rdfind
    - symlinks
    - systemtap-sdt-dev
    - libaudit-dev
    - g++-5
    - wget
    - quilt
    - gawk
    - debhelper
    - bison
